### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by Yuliya-beCode** [Yuliya-beCode/Javascript#1]
Hi girls,

as already discussed, we have set our first meeting

on 15.02. at 11h00 am. 

Agenda points:
1. Figma design
2. html structure
3. js structure. 

It will be a pleasure to meet you on Monday ;-)

Kind regards,
Yuliya

**Comment by Doringl** [comment]
Hello, can i help you on your project?

**Comment by Yuliya-beCode** [comment]
Dear Doringl,

thanks a lot for your email 👍 

As this project is to be considered to evaluate our skills, unfortunately, we cannot consider your help. 

Thanks again for your proposal and have a good day!

Best regards,
Yuliya

> Hello, can i help you on your project?
